# Global configuration
global:
  scrape_interval: 15s  # Interval for scraping (15 sekunder)



# Scrape configuration
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus server itself

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Grafana, hvis du har metrics eksponeret der (fx via en plugin)
